INSERT INTO USERS VALUES (USERS_SEQ.nextval, 'hellonewtry1@gmail.com', '1111', '코딩하실분', ' ');
INSERT INTO USERS VALUES (USERS_SEQ.nextval, 'anhongyong@gmail.com', '2222', '안홍용', ' ');
INSERT INTO USERS VALUES (USERS_SEQ.nextval, 'parkchanju@gmail.com', '3333', '박찬주', ' ');
INSERT INTO USERS VALUES (USERS_SEQ.nextval, 'kimwonsik@gmail.com', '4444', '김원식', ' ');

INSERT INTO CATEGORY VALUES (CATEGORY_SEQ.nextval, 'HTML/CSS');
INSERT INTO CATEGORY VALUES (CATEGORY_SEQ.nextval, '웹 개발');
INSERT INTO CATEGORY VALUES (CATEGORY_SEQ.nextval, 'JavaScript');
INSERT INTO CATEGORY VALUES (CATEGORY_SEQ.nextval, 'Java');
INSERT INTO CATEGORY VALUES (CATEGORY_SEQ.nextval, 'Front-End');
INSERT INTO CATEGORY VALUES (CATEGORY_SEQ.nextval, 'Python');
INSERT INTO CATEGORY VALUES (CATEGORY_SEQ.nextval, 'Back-End');
INSERT INTO CATEGORY VALUES (CATEGORY_SEQ.nextval, '웹 퍼블리싱');
INSERT INTO CATEGORY VALUES (CATEGORY_SEQ.nextval, 'Spring');
INSERT INTO CATEGORY VALUES (CATEGORY_SEQ.nextval, 'Node.js');
INSERT INTO CATEGORY VALUES (CATEGORY_SEQ.nextval, 'React');

INSERT INTO INSTRUCTOR VALUES (INSTRUCTOR_SEQ.nextval, '최대한', ' ');
INSERT INTO INSTRUCTOR VALUES (INSTRUCTOR_SEQ.nextval, '김원식', ' ');
INSERT INTO INSTRUCTOR VALUES (INSTRUCTOR_SEQ.nextval, '안홍용', ' ');
INSERT INTO INSTRUCTOR VALUES (INSTRUCTOR_SEQ.nextval, '박찬주', ' ');

INSERT INTO LECTURE VALUES (LECTURE_SEQ.nextval, 1, 1, '파이썬을 배워보자', ' ', 5000, '초급', ' ', sysdate);
INSERT INTO LECTURE VALUES (LECTURE_SEQ.nextval, 2, 2, '자바를 배워보자', ' ',5000, '초급', ' ', sysdate);
INSERT INTO LECTURE VALUES (LECTURE_SEQ.nextval, 3, 3, 'JSP를 배워보자', ' ',15000, '초급', ' ', sysdate);
INSERT INTO LECTURE VALUES (LECTURE_SEQ.nextval, 4, 4, 'SPRING을 배워보자', ' ', 50000, '초급', ' ', sysdate);

INSERT INTO CURRICULUM VALUES (CURRICULUM_SEQ.nextval, 1, ' ', ' ', ' ',  500);
INSERT INTO CURRICULUM VALUES (CURRICULUM_SEQ.nextval, 1, ' ', ' ', ' ',  500);
INSERT INTO CURRICULUM VALUES (CURRICULUM_SEQ.nextval, 1, ' ', ' ', ' ',  500);
INSERT INTO CURRICULUM VALUES (CURRICULUM_SEQ.nextval, 1, ' ', ' ', ' ',  500);
INSERT INTO CURRICULUM VALUES (CURRICULUM_SEQ.nextval, 1, ' ', ' ', ' ',  500);
INSERT INTO CURRICULUM VALUES (CURRICULUM_SEQ.nextval, 1, ' ', ' ', ' ',  500);
INSERT INTO CURRICULUM VALUES (CURRICULUM_SEQ.nextval, 1, ' ', ' ', ' ',  500);
INSERT INTO CURRICULUM VALUES (CURRICULUM_SEQ.nextval, 1, ' ', ' ', ' ',  500);

INSERT INTO CURRICULUM VALUES (CURRICULUM_SEQ.nextval, 2, ' ', ' ', ' ',  500);
INSERT INTO CURRICULUM VALUES (CURRICULUM_SEQ.nextval, 2, ' ', ' ', ' ',  500);
INSERT INTO CURRICULUM VALUES (CURRICULUM_SEQ.nextval, 2, ' ', ' ', ' ',  500);
INSERT INTO CURRICULUM VALUES (CURRICULUM_SEQ.nextval, 2, ' ', ' ', ' ',  500);
INSERT INTO CURRICULUM VALUES (CURRICULUM_SEQ.nextval, 2, ' ', ' ', ' ',  500);
INSERT INTO CURRICULUM VALUES (CURRICULUM_SEQ.nextval, 2, ' ', ' ', ' ',  500);
INSERT INTO CURRICULUM VALUES (CURRICULUM_SEQ.nextval, 2, ' ', ' ', ' ',  500);

INSERT INTO CURRICULUM VALUES (CURRICULUM_SEQ.nextval, 3, ' ', ' ', ' ',  500);
INSERT INTO CURRICULUM VALUES (CURRICULUM_SEQ.nextval, 3, ' ', ' ', ' ',  500);
INSERT INTO CURRICULUM VALUES (CURRICULUM_SEQ.nextval, 3, ' ', ' ', ' ',  500);

INSERT INTO CURRICULUM VALUES (CURRICULUM_SEQ.nextval, 4, ' ', ' ', ' ',  500);
INSERT INTO CURRICULUM VALUES (CURRICULUM_SEQ.nextval, 4, ' ', ' ', ' ',  500);
INSERT INTO CURRICULUM VALUES (CURRICULUM_SEQ.nextval, 4, ' ', ' ', ' ',  500);
INSERT INTO CURRICULUM VALUES (CURRICULUM_SEQ.nextval, 4, ' ', ' ', ' ',  500);
INSERT INTO CURRICULUM VALUES (CURRICULUM_SEQ.nextval, 4, ' ', ' ', ' ',  500);

INSERT INTO FINISH VALUES (1, 1, 1, 0, SYSDATE);
INSERT INTO FINISH VALUES (1, 1, 2, 0, SYSDATE);
INSERT INTO FINISH VALUES (1, 1, 3, 1, SYSDATE);
INSERT INTO FINISH VALUES (1, 1, 4, 0, SYSDATE);
INSERT INTO FINISH VALUES (1, 1, 5, 0, SYSDATE);
INSERT INTO FINISH VALUES (1, 1, 6, 1, SYSDATE);
INSERT INTO FINISH VALUES (1, 1, 7, 0, SYSDATE);
INSERT INTO FINISH VALUES (1, 1, 8, 0, SYSDATE);

INSERT INTO FINISH VALUES (4, 2, 9, 0, SYSDATE);
INSERT INTO FINISH VALUES (4, 2, 10, 0, SYSDATE);
INSERT INTO FINISH VALUES (4, 2, 11, 1, SYSDATE);
INSERT INTO FINISH VALUES (4, 2, 12, 1, SYSDATE);
INSERT INTO FINISH VALUES (4, 2, 13, 1, SYSDATE);
INSERT INTO FINISH VALUES (4, 2, 14, 1, SYSDATE);
INSERT INTO FINISH VALUES (4, 2, 15, 1, SYSDATE);

INSERT INTO FINISH VALUES (2, 3, 16, 0, SYSDATE);
INSERT INTO FINISH VALUES (2, 3, 17, 1, SYSDATE);
INSERT INTO FINISH VALUES (2, 3, 18, 1, SYSDATE);

INSERT INTO FINISH VALUES (3, 4, 19, 1, SYSDATE);
INSERT INTO FINISH VALUES (3, 4, 20, 1, SYSDATE);
INSERT INTO FINISH VALUES (3, 4, 21, 1, SYSDATE);
INSERT INTO FINISH VALUES (3, 4, 22, 1, SYSDATE);
INSERT INTO FINISH VALUES (3, 4, 23, 1, SYSDATE);



SELECT * FROM USERS;
SELECT * FROM CATEGORY;
SELECT * FROM INSTRUCTOR;
SELECT * FROM LECTURE;
SELECT * FROM CURRICULUM;
SELECT * FROM FINISH;


commit;